### ISSUE TITLE
Build instruction tweak

### ISSUE THREAD

**Issue by SamyBencherif** [ionyshch/cmake-bundle-macos#1]
Hello, nice project!

For me the existing build instructions did not quite work but the following seems to have:

```
mkdir build
cd build
cmake ..
cd ..             # this line is added
cpack -G DragNDrop
```

**Comment by ionyshch** [comment]
Thank you for feedback @SamyBencherif 
Will consider updating docs once there are more people with the issue you've encountered. For now will just close and issue.
