### ISSUE TITLE
Doesn't bundle the dylibs in the .app bundle

### ISSUE THREAD

**Issue by shakfu** [ionyshch/cmake-bundle-macos#4]
For me it doesn't bundle or copy the dynamic libraries inside the bundle. Is there an extra config step for this?

**Comment by shakfu** [comment]
Incidentally, I fixed this in my [fork](https://github.com/shakfu/cmake-bundle-macos) with a utility called [macdylibbundler](https://github.com/auriamg/macdylibbundler). 

There must be a pure cmake way to do this. I'd appreciate if someone who the way.

**Comment by ionyshch** [comment]
Please, provide steps to reproduce the issue and describe your environment: OS version, libraries version.

**Comment by shakfu** [comment]
I cloned your repo, `mkdir build && cd build`, `cmake ..`, `make`

I'm on macOS OSX Monterey MacBook intel, cmake version 3.24.3

In your case, does it copy the `*.dylib` into the bundle? If so, into what folders?

**Comment by shakfu** [comment]
My mistake, I wasn't running `cpack -G DragNDrop` it works now without issues.

Thanks for sharing, project was very helpful!
